// SPDX-FileCopyrightText: 2026 Matthew McDade <nvllmnd@pm.me>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include "nv/core/algo.h"
#include "nv/core/attributes.h"
#include "nv/core/constants.h"
#include "nv/core/intdefs.h"
#include "nv/core/core_types.h"
#include "nv/memory/layout.h"

/// @brief Minimum size
static constexpr const i32 STATIC_ALLOC_MIN_SIZE = 24;

/// @brief 'base type' for any size StaticAlloc
/// @details Arena-style static memory allocator. Ive typedefed some sizes, increasing by powers of 2,
/// The [TStaticAlloc] and [DEF_STATIC_ALLOC] macros are provided if you wish to proivde you own sizes.
/// There is a ~24 byte header that is placed at the very start of the StaticAlloc type that is generated by using the
/// [TStaticAlloc] macro (or   EF_STATIC_ALLOC])
typedef struct StaticAlloc StaticAlloc;

#define TStaticAlloc(N) \
  struct {              \
    u8 storage[N];      \
  }

#define DEF_STATIC_ALLOC(N, _name)                                           \
  static_assert(sizeof(__typeof(TStaticAlloc(N))) >= STATIC_ALLOC_MIN_SIZE); \
  typedef TStaticAlloc(N) _name

DEF_STATIC_ALLOC(KILOBYTES(4), StaticAlloc4k);

DEF_STATIC_ALLOC(KILOBYTES(8), StaticAlloc8k);
// DEF_STATIC_ALLOC(KILOBYTES(12), StaticAlloc12k);
DEF_STATIC_ALLOC(KILOBYTES(16), StaticAlloc16k);

DEF_STATIC_ALLOC(KILOBYTES(24), StaticAlloc24k);

DEF_STATIC_ALLOC(KILOBYTES(32), StaticAlloc32k);

DEF_STATIC_ALLOC(KILOBYTES(64), StaticAlloc64k);
DEF_STATIC_ALLOC(KILOBYTES(128), StaticAlloc128k);

DEF_STATIC_ALLOC(KILOBYTES(255), StaticAlloc255k);
DEF_STATIC_ALLOC(KILOBYTES(512), StaticAlloc512k);

DEF_STATIC_ALLOC(MEGABYTES(1), StaticAlloc1mb);
DEF_STATIC_ALLOC(MEGABYTES(2), StaticAlloc2mb);

DEF_STATIC_ALLOC(MEGABYTES(4), StaticAlloc4mb);
DEF_STATIC_ALLOC(MEGABYTES(8), StaticAlloc8mb);

DEF_STATIC_ALLOC(MEGABYTES(16), StaticAlloc16mb);
DEF_STATIC_ALLOC(MEGABYTES(24), StaticAlloc24mb);

#define salloc_capacity(_self) (sizeof(__typeof((_self).storage)))
#define salloc_begin(_self) (&(_self).storage[0])
#define salloc_end(_self) (salloc_begin(_self) + salloc_capacity(_self))

#define salloc_ref(_self) ((StaticAlloc*)salloc_begin(_self))

#define salloc_cref(_self) ((const StaticAlloc*)salloc_begin(_self))
// #define salloc_used(_self) ((_self).top - salloc_begin(_self))
// #define salloc_ref(_self) (make(StaticAllocRef, .top = &(_self.top), .storage = { .start = &(_self).storage[0], .end
// = &(_self).storage[sizeof(__typeof((_self.storage)))] })

#define salloc_new(N) (make_zeroed(TStaticAlloc(N)))

METHOD
void salloc_init_(StaticAlloc* self, i32 size_bytes);
#define salloc_init(_self) (salloc_init_(salloc_ref(_self), salloc_capacity(_self)))

METHOD
PURE_FUNC
i32 salloc_used(const StaticAlloc* self);

METHOD
void* salloc_allocate(StaticAlloc* self, Layout layout) WHERE(IS_POWER_OF_2(layout.align));

METHOD
void* salloc_zallocate(StaticAlloc* self, Layout layout) WHERE(IS_POWER_OF_2(layout.align));

PARAMS_NONNULL(1, 2)
void* salloc_expand(StaticAlloc* self, void* ptr, Layout old_layout, Layout new_layout)
    WHERE(IS_POWER_OF_2(old_layout.align) && IS_POWER_OF_2(new_layout.align));

PARAMS_NONNULL(1, 2)
void* salloc_reallocate(StaticAlloc* self, void* ptr, Layout old_layout, Layout new_layout)
    WHERE(IS_POWER_OF_2(old_layout.align) && IS_POWER_OF_2(new_layout.align));

PARAMS_NONNULL(1, 2)
char* salloc_strndup(StaticAlloc* self, const char* string, i32 n) WHERE(n > 0);

CONST_FUNC
i32 salloc_metadata_size(void);
